apiVersion: apps/v1
kind: Deployment
metadata:
  name:  photo-studio-deployment
  namespace: photostudio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photo-studio
  template:
    metadata:
      labels:
        app: photo-studio
    spec:
      containers:
        - name: photo-studio
          image: norahbiju/photostudio-node:v1
          env:
            - name: MONGODB_AUTH_URI
              valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MONGODB_AUTH_URI
            - name: MONGODB_URI
              valueFrom:
              secretKeyRef:
                name: app-secrets
                key: MONGODB_URI
          ports:
            - containerPort: 3000
---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: photostudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb  
    spec:  
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
 
