apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: photostudio
type: Opaque
stringData:
  PORT: "3000"
  MONGODB_URI: "mongodb://mongodb-service:27017"
  MONGODB_AUTH_URI: "mongodb://mongodb-service:27017/artgallery"
  MONGODB_FEEDBACK_URI: "mongodb://mongodb-service:27017/artgallery
  
